### ISSUE TITLE
Unale to build from Dockerfile

### ISSUE THREAD

**Issue by susmitameher** [prometheus-community/json_exporter#100]
Hi,
I am trying to build this from Dockerfile as my docker ARCH="x86_64"  and  I want to change the EXPOSE port. However it is always complaining while copying file path. _COPY failed: stat /var/lib/docker/tmp/docker-builder688375406/.build/linux-x86_64/json_exporter: no such file or directory_

**Comment by cweiwenr** [comment]
Hi, have you found a solution to this?

**Comment by susmitameher** [comment]
Path issue has been fixed, and using the customized port.
