### ISSUE TITLE
json_exporter offline configuration/install

### ISSUE THREAD

**Issue by taadeel4** [prometheus-community/json_exporter#101]
Hello everyone,

Is there any way to install / configure the json_exporter without any Internet Access ?
I am working in a project and I'd like to bring prometheus to monitor some nodes (Packet Brokers) that I cant run node_exporter. 
Those nodes have exposed metrics via JSON.

However, im not allowed to have any internet access directly to any node, but I can upload anything via FTP.

The ideia is to have the following 

Prometheus -->scrape-->**JSON Exporter (CENTOS 7.9)**-->reaches out to-->Packet Broker. 

I've tried to upload the json_exporter and install it with make , but no success :

-bash-4.2# make
>> checking code style
>> checking license header
mkdir -p /root/go/bin
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.39.0/install.sh \
        | sed -e '/install -d/d' \
        | sh -s -- -b /root/go/bin v1.39.0
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
go: github.com/go-kit/kit@v0.10.0: Get "https://proxy.golang.org/github.com/go-kit/kit/@v/v0.10.0.mod": dial tcp: lookup proxy.golang.org on 8.8.8.8:53: read udp 10.180.24.89:48442->8.8.8.8:53: read: connection refused
make: *** [common-lint] Error 1
-bash-4.2# 

I have a Centos 7.8 running
**-bash-4.2# uname -a**
Linux localhost.localdomain 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**-bash-4.2# go version**
go version go1.16.4 linux/amd64
**-bash-4.2# gcc --version**
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CentOS Linux release 7.8.2003 (Core)

Thank you in advanced

Br
Elton

**Comment by susmitameher** [comment]
Hi,
I had even the same issue few days back, although I was using it on a Linux box with no internet.
Later, I used the docker image available and somehow managed to add it to company repository and from there Json Exporter is working completely fine from last few days.

**Comment by taadeel4** [comment]
Hi susmitameher,
Thanks for your answer.
So basically, I will have to somehow install docker on my Centos to make it work ?

Br
Elton

**Comment by rustycl0ck** [comment]
You can find the binaries of the latest release here - https://github.com/prometheus-community/json_exporter/releases

**Comment by taadeel4** [comment]
Hi rustyl0ck,

Thanks a lot for the link,  it solved all my problems !! Thanks a lot !
