### ISSUE TITLE
Failed to convert extracted value to float64

### ISSUE THREAD

**Issue by ckocyigit** [prometheus-community/json_exporter#121]
Hello,

somehow the exporter keeps failing with this message to me:

"Failed to convert extracted value to float64"

Iam trying to scrape a relatively big Json file through URL. 

The json-exporter config:

```
metrics:  
  - name: backends
    path: "{$.status}"
    help: Exporting JSON Health Actuator from Backends
```

The json-exporter log when executing following as HTTP GET:

`https://json-exporter-XXXXX-json-exporter.apps.os4.XXXXX.net/probe?target=http://backend.XXXXX.svc.cluster.local:8080/api/actuator/health`

```
level=info ts=2021-09-14T10:11:32.189Z caller=main.go:52 msg="Starting json_exporter" version="(version=0.3.0, branch=HEAD, revision=ae58e1f3e7161fb2a2a90a16998db0c072e2d532)"
level=info ts=2021-09-14T10:11:32.189Z caller=main.go:53 msg="Build context" build="(go=go1.15.8, user=root@46db6777a64c, date=20210214-02:17:04)"
level=info ts=2021-09-14T10:11:32.189Z caller=main.go:55 msg="Loading config file" file=/tmp/config.yml
level=info ts=2021-09-14T10:11:32.189Z caller=main.go:65 msg="Loaded config file" config="{\"Headers\":null,\"Metrics\":[{\"Name\":\"backends\",\"Path\":\"{$.status}\",\"Labels\":null,\"Type\":\"value\",\"Help\":\"Exporting JSON Health Actuator from Backends\",\"Values\":null}],\"HTTPClientConfig\":{\"BasicAuth\":null,\"BearerToken\":\"\",\"BearerTokenFile\":\"\",\"ProxyURL\":{},\"TLSConfig\":{\"CAFile\":\"\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ServerName\":\"\",\"InsecureSkipVerify\":false}}}"
level=info ts=2021-09-14T10:11:32.190Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=error ts=2021-09-14T10:12:39.511Z caller=collector.go:63 msg="**Failed to convert extracted value to float64**" path={$.status} value=DOWN err="strconv.ParseFloat: parsing \"DOWN\": invalid syntax; strconv.ParseBool: parsing \"DOWN\": invalid syntax" metric="Desc{fqName: \"backends\", help: \"Exporting JSON Health Actuator from Backends\", constLabels: {}, variableLabels: []}"

```

**Comment by ckocyigit** [comment]
Seems like the parameter type was missing but also I can only export number fields no strings somehow

`metrics:  
- name: Backend
  path: "{$}"
  type: value
  help: Backend overall status
  values:
    Status: "{.status}" # does not work

- name: Components
  path: "{$.components}"
  type: object
  help: This are the component statuses of the backend
  values:
    DiskSpaceStatus: '{.diskSpace.status}' # does not work
    DiskSpaceTotal: '{.diskSpace.details.total}' # works
    DiskSpaceFree: '{.diskSpace.details.free}' # works
    DiskSpaceThreshold: '{.diskSpace.details.threshold}'` # works

**Comment by JT1301** [comment]
Can you post your current config? I just want to do the exact same thing, but I can't get it to run.
