### ISSUE TITLE
Multiple end points?

### ISSUE THREAD

**Issue by VR6Pete** [prometheus-community/json_exporter#14]
I use this exporter for a bespoke system spitting out some json content. Works great however I have another 100+ application servers I would like to pull into Prometheus. 

How does this product scale? From my limited understanding the read me suggests only a single url and config can be passed into the exporter. 

Can you please advise how I can use this on scale for multiple instances ?

**Comment by VR6Pete** [comment]
Is this project still alive ?

**Comment by VR6Pete** [comment]
Still seeking advice on this topic. 

Thanks. 

Pete

**Comment by lindhor** [comment]
Supporting multiple endpoints would be a great addition.

**Comment by SuperQ** [comment]
Now that we've got this in Prometheus Community, it would be nice to have some contributions. PRs welcome.

**Comment by rustycl0ck** [comment]
I'll start working on this. I'm thinking about doing it just like the blackbox exporter does it (serve at the `/probe` endpoint with `target` as the custom parameter which is the REST API endpoint to be scraped).

Let me know if this sounds good.

**Comment by SuperQ** [comment]
Yes, following the blackbox exporter pattern sounds good to me.

**Comment by rustycl0ck** [comment]
This is now available in #49

**Comment by sgoodliff** [comment]
Hi, 

Any ideas when this might get merged, ? I would be very pleased to use it to replace telegraf instances that  export to prometheus

thanks

**Comment by SuperQ** [comment]
This is now done.

**Comment by crockk** [comment]
This was a great addition, however I'm not sure if there is any way to filter within the config which rules apply to which targets? IE, all your rules in your config YAML will be applied to all your targets, resulting in a huge amount of errors for the mismatched rules. The ones that are supposed to work still work, but the same rule will be applied to every result from every endpoint.

**Comment by pete-leese** [comment]
Hi - Looks like I am late to the game after not needing to use this exporter for a number of years. 

I have a number of API endpoints I wish to scrape across - What would the config.yml look like to ensure I am not getting the issues described by above comment to ensure I can tie specific rules to a target as would be undesirable for the same rules to be applied to every target. 

Hopefully @SuperQ  or @rustycl0ck can assist? :)

**Comment by SuperQ** [comment]
@pete-leese Supporting multiple config modules is a new feature request. The config will need to be refactored to support an additional target param, kinda like the blackbox_exporter `module` param.

**Comment by EvilJordan** [comment]
Any movement on this? I got multiple targets working, but also see the errors. Not sure if it _really_ matters, but I imagine keeping logs clean would be a good thing. Thank you for building this!!
