### ISSUE TITLE
Ignore http status in answer

### ISSUE THREAD

**Issue by sepich** [prometheus-community/json_exporter#160]
There are some cases whet target still returns valid json, but http status is not 2xx.
For example gradle enterprise has such endpoint:
```
$ curl -i https://gradle.domain.local/ready
HTTP/2 503
date: Thu, 23 Jun 2022 10:24:55 GMT
content-type: application/json
strict-transport-security: max-age=15724800; includeSubDomains


{"build_cache_node":false,"enterprise_app":true,"keycloak":true,"test_distribution":true}
```
It returns HTTP 200, when all components are ready, and 503 when any of them is down (`build_cache_node` in this case)
It is done, so that `/ready` endpoint could be used for http healthchecks.
But we want still continue to collect all components statuses from json with json-exporter when the answer is 503.
Current results is:
```
curl -i 'localhost:7979/probe?module=gradle-ready&target=https://gradle.domain.local/ready'
HTTP/1.1 503 Service Unavailable
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 27 Jun 2022 16:40:59 GMT
Content-Length: 93

Failed to fetch JSON response. TARGET: https://gradle.domain.local/ready, ERROR: 503 Service Unavailable
```

Is it possible to add some additional param, like `ignore_status: true` to module definition?
So that scrape would be failed only in 'invalid json' case.
Thank you!

**Comment by ilanni2460** [comment]
valid_status_codes: [200,503]
