### ISSUE TITLE
Make on Raspi4 go version go1.11.6 linux/arm raises many errors

### ISSUE THREAD

**Issue by zwuba** [prometheus-community/json_exporter#219]
Dear community,

first of sorry this might be a noob question but after hours and hours of searching I ran out of ideas ...

So I'm trying to make json_exporter on my Raspi4 using the 'make' command (I manually installed the latest version of Go for ARMv6) and it posts a huge list of required packages.
This is last line printed:
make: *** [Makefile.common:193: common-unused] Error 1

I tried to load as many of them using 'go get xxx' but that only resolved a few of them (now showing a + instead of a - in front).

>> running check for unused/missing packages in go.mod
go mod tidy
diff --git a/go.mod b/go.mod
index e289f24..4f6dde1 100644
--- a/go.mod
+++ b/go.mod
@@ -14,34 +14,14 @@ require (
 )
 
 require (
-       github.com/Masterminds/goutils v1.1.1 // indirect
-       github.com/Masterminds/semver/v3 v3.2.0 // indirect
-       github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 // indirect
-       github.com/alecthomas/units v0.0.0-20211218093645-b94a6e3cc137 // indirect
-       github.com/beorn7/perks v1.0.1 // indirect
-       github.com/cespare/xxhash/v2 v2.1.2 // indirect
-       github.com/coreos/go-systemd/v22 v22.4.0 // indirect
-       github.com/go-logfmt/logfmt v0.5.1 // indirect
-       github.com/golang/protobuf v1.5.2 // indirect
-       github.com/google/uuid v1.1.2 // indirect
-       github.com/huandu/xstrings v1.3.3 // indirect
-       github.com/imdario/mergo v0.3.11 // indirect
-       github.com/jpillora/backoff v1.0.0 // indirect
-       github.com/kr/pretty v0.3.0 // indirect
-       github.com/matttproud/golang_protobuf_extensions v1.0.4 // indirect
-       github.com/mitchellh/copystructure v1.0.0 // indirect
-       github.com/mitchellh/reflectwalk v1.0.0 // indirect
-       github.com/mwitkow/go-conntrack v0.0.0-20190716064945-2f068394615f // indirect
-       github.com/prometheus/client_model v0.3.0 // indirect
-       github.com/prometheus/procfs v0.8.0 // indirect
-       github.com/shopspring/decimal v1.2.0 // indirect
-       github.com/spf13/cast v1.3.1 // indirect
-       golang.org/x/crypto v0.3.0 // indirect
-       golang.org/x/net v0.7.0 // indirect
-       golang.org/x/oauth2 v0.3.0 // indirect
-       golang.org/x/sync v0.1.0 // indirect
-       golang.org/x/sys v0.5.0 // indirect
-       golang.org/x/text v0.7.0 // indirect
-       google.golang.org/appengine v1.6.7 // indirect
-       google.golang.org/protobuf v1.28.1 // indirect
+       github.com/golang/protobuf v1.5.3 // indirect
+       github.com/google/uuid v1.3.0 // indirect
+       github.com/huandu/xstrings v1.4.0 // indirect
+       github.com/imdario/mergo v0.3.13 // indirect
+       github.com/kr/pretty v0.3.1 // indirect
+       github.com/mitchellh/copystructure v1.2.0 // indirect
+       github.com/prometheus/procfs v0.9.0 // indirect
+       github.com/shopspring/decimal v1.3.1 // indirect
+       golang.org/x/crypto v0.7.0 // indirect
+       google.golang.org/protobuf v1.29.0 // indirect
 )

After that I'm getting a few hundred lines that look like this - not sure if that's good or bad:
gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
 gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
 gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
+gopkg.in/yaml.v3 v3.0.0/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
 gopkg.in/yaml.v3 v3.0.1 h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
 gopkg.in/yaml.v3 v3.0.1/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=

**Comment by SuperQ** [comment]
At least Go 1.17 is required to build. That version of Go is too old.
