### ISSUE TITLE
config question

### ISSUE THREAD

**Issue by jhoustek23** [prometheus-community/json_exporter#271]
I have alertmanger, which is returning (i.e.):
`[
  {
    "annotations": {
      "description": "related dashboard https://monitoring.pricefx.eu/grafana/goto/3fP56O8Vz?orgId=1",
      "summary": "Job pods are pending(not running) for more than 15min. Check the reason. Could be singal that customer need higher taskPoolSize or we need more nodes to scale"
    },
    "endsAt": "2023-11-02T15:15:02.673Z",
    "fingerprint": "026e96fbc7eef2ba",
    "receivers": [
      {
        "name": "ops-support_warning"
      }
    ],
    "startsAt": "2023-11-02T03:25:02.673Z",
    "status": {
      "inhibitedBy": [],
      "silencedBy": [],
      "state": "active"
    },
    "updatedAt": "2023-11-02T15:11:02.791Z",
    "labels": {
      "alertname": "JOBS_Pending",
      "k8s_cluster": "core_prod_1_eu-west-1",
      "namespace": "monitoring",
      "pod": "loki-promtail-k7sbv",
      "severity": "warning",
      "team": "ops,support"
    }
  }
]`

With config.yml:
`
---
modules:
  default:
    metrics:
    - name: Alertmanager
      type: object
      path: '{ [*] }'
      labels:
        alertname: '{ .labels.alertname }'
        severity: '{ .labels.severity }'
        status: '{.status.state}'
      values:
        account: '{ .labels.account }'
      help: Alertmanager_status_test`

curl "http://localhost:7979/probe?module=default&target=http://localhost:9093/alertmanager/api/v2/alerts"

* collected metric "Alertmanager_account" { label:{name:"alertname" value:"JOBS_Pending"} label:{name:"severity" value:"warning"} label:{name:"status" value:"active"} untyped:{value:1.50147641088e+11}} was collected before with the same name and label values

What I'm doing wrong?
Thanks!

**Comment by Jaypers** [comment]
You have to include some unique labels in your query so that the metrics are somehow unique.

An ID or fingerprint label is ideal for this but in a worst case you could try include timestamps.
