### ISSUE TITLE
Option to customize the interface to bind

### ISSUE THREAD

**Issue by anthony-pastor** [prometheus-community/json_exporter#31]
It'd be nice to have an option to customize the interface(s) to be exposed.
For instance to only listen to localhost.

`netstat -tupan | grep 7979`
`tcp6       0      0 :::7979                 :::*                    LISTEN      20908/./json_export`

**Comment by SuperQ** [comment]
This is now fixed, you can use `--web.listen-address`

**Comment by anthony-pastor** [comment]
Thanks @SuperQ
