### ISSUE TITLE
only id data parsing

### ISSUE THREAD

**Issue by ranjitm74** [prometheus-community/json_exporter#82]
If I try to get data from below json format from my .net json api 
{
  "values": [
    {
      "id": "2021-01-19T17:36:59.627",
      "count": "15.00.16.02.01",
      "some_boolean": "15.00.16.02.011-01-01",
      "module": "Batch",
      "state": "ACTIVE"
    },
    {
      "id": "2021-01-19T17:36:59.628",
      "count": "15.00.16.02.02",
      "some_boolean": "15.00.16.02.011-01-02",
      "state": "INACTIVE"
    },
    {
      "id": "2021-01-19T17:36:59.629",
      "count": "15.00.16.02.03",
      "some_boolean": "15.00.16.02.011-01-03",
      "state": "ACTIVE"
    }
  ]
}

Its only parsing "id" 
rest all giving error 
Kindly help me to get data from diff format given below 
{
  "values": [
    {
      "id": "2021-01-19T17:36:59.627",
      "count": "15.00.16.02.01",
      "some_boolean": "15.00.16.02.011-01-01",
      "module": "Batch",
      "state": "ACTIVE"
    },
    {
      "id": "2021-01-19T17:36:59.628",
      "count": "15.00.16.02.02",
      "some_boolean": "15.00.16.02.011-01-02",
      "module": "Batch1",
      "state": "INACTIVE"
    },
    {
      "id": "2021-01-19T17:36:59.629",
      "count": "15.00.16.02.03",
      "some_boolean": "15.00.16.02.011-01-03",
      "module": "Batch2",
      "state": "ACTIVE"
    }
  ]
}

I tried to modify using given json but  could get only "id" data into prom 2021-01-19T17:36:59.629, rest all giving error

waiting for your reply

**Comment by ranjitm74** [comment]
can we get all other data read as "id" only, 

bcos non other data are like "count" or "boolean"

**Comment by rustycl0ck** [comment]
Please verify if the data you want to collect can be exported as time series or not. You can read more about Prometheus [data model](https://prometheus.io/docs/concepts/data_model/) and [metric types](https://prometheus.io/docs/concepts/metric_types/). 

You can also try to use metric labels for enumeration in some cases.
