### ISSUE TITLE
Multi probe target with different username/password

### ISSUE THREAD

**Issue by kunkka234** [prometheus-community/json_exporter#86]
Hi, I'm a beginner of json_exporter and wondering is it possible to probe multiple target with different auth info

**What i want:**
one json_exporter container that can probe `exampleA.com/dataA.json` with  basic auth `userName1/passwd1`,
and probe `exampleB.com/dataB.json` with `userName2/passwd2` in the same time.

looking forward to you kindly replys.

**Comment by SuperQ** [comment]
Supporting multiple configurations "module" instances and multiple "http_client_config" sections would be useful.
