### ISSUE TITLE
Scrape JSON from a (HTTPS) REST API with bearer token authentication

### ISSUE THREAD

**Issue by frank-1970** [prometheus-community/json_exporter#90]
I am a newbie at prometheus and exporters so beforehand, apologies for any stupid questions, assumptions, etc.

I have an application that exposes a REST API that I want to scrape so I can use the metrics in Prometheus/Grafana. The json-exporter looks like a good fit for this but after reading the documentation I concluded that I can only use the json_exporter to scrape REST API's that use plain HTTP.

The REST API I am dealing with only supports secured (SSL/HTTPS) API calls. More specifically, I have to get an OAUTH 2.0 token (POST with username, password and grant-type set to ' password') and next, with this (bearer) token I query all the metrics.

Is there any way to make this work with the json_exporter? Can I configure the json_exporter to scrape a HTTPS REST API endpoint? And does this work with bearer tokens? (the REST API endpoint does not support basic authentication)

**Comment by f33r0** [comment]
How did you solve the problem?
