### ISSUE TITLE
Copy blackbox_exporter's support of basic_auth for targets

### ISSUE THREAD

**Issue by Drugoy** [prometheus-community/json_exporter#93]
Blackbox_exporter [supports](https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#http_probe) basic_auth block for **targets**.
```
  # The HTTP basic authentication credentials for the targets.
  basic_auth:
    [ username: <string> ]
    [ password: <secret> ]
    [ password_file: <filename> ]
```

Json_exporter should too.

**Comment by Drugoy** [comment]
Edit: just noticed that 2nd option is actually not viable at all (didn't notice errors in the log).
Feel free to close this ticket if it's local just to json_exporter and needs to be fixed there.

**Comment by SuperQ** [comment]
This is already implemented in the configuration file under [`http_cient_config`](https://github.com/prometheus-community/json_exporter/blob/1ad3cb274d2edfc054d6085df2b385cf0cd2ba5b/examples/config.yml#L25-L33).
