### ISSUE TITLE
Docker container eating disk space

### ISSUE THREAD

**Issue by crockk** [prometheus-community/json_exporter#99]
Hi everyone, I noticed my deployment of the json_exporter is eating up a huge amount of filesystem after running for just about a week:

```
root@prometheus1:/var/lib/docker/containers# du -hs * | sort -hr
236G    c898acc7c656762012e1077c54bac17ba141ac63603f9bbce465873bc582b770
3.2G    a7ad30b813322bf2b37b8bcf971ec10c4f8a9bd28cfde8841221fe5da3bfe37a
7.8M    bc57bf081a7de91204a7cb3b461a69fa8dadfacb484faef7a06155482daa63bd
232K    2efaf8b89913a16295d679bbde498dfde616d36f59e0015452fbc4afab8a2e7e
44K     f9d65b9e7403f21974d9e1b2f7861aa7b3e9e1fa3daaffac4d67959e7b908cea
40K     a2716929d9d17f221eee69f0642b867ef3e12098cadd4770583e5cd0c4fa0ef4
40K     76eaff2917edbd35fa15c5c80b9779f5f3a6a0c084cac16a100a94bdcb8524dc
40K     4717535b32a9d814a8f3a322cdfb524d6ae25503207f8f3cf1c5ef49e1823f19
28K     7ae414e3301a376455d9b7f8d313ed11d9e682325aacaaadac86abf9e14905c9
root@prometheus1:/var/lib/docker/containers# docker ps
CONTAINER ID   IMAGE                                       COMMAND                  CREATED       STATUS        PORTS                    NAMES
2efaf8b89913   ribbybibby/ssl-exporter:latest              "/ssl_exporter --con…"   5 days ago    Up 39 hours   0.0.0.0:xxx->9219/tcp   ssl_exporter
c898acc7c656   quay.io/prometheuscommunity/json-exporter   "/bin/json_exporter …"   7 days ago    Up 43 hours   0.0.0.0:xxx->7979/tcp   json_exporter
bc57bf081a7d   mogensen/cert-checker:latest                "/app/cert-checker"      10 days ago   Up 43 hours   0.0.0.0:xxx->8080/tcp   cert_checker
a7ad30b81332   ghcr.io/prymitive/karma:v0.82               "/karma"                 4 weeks ago   Up 42 hours   0.0.0.0:xxx->8080/tcp   karma
f9d65b9e7403   prom/blackbox-exporter:master               "/bin/blackbox_expor…"   6 weeks ago   Up 39 hours   0.0.0.0:xxx->9115/tcp   blackbox_exporter
```

What could be causing this? I'm using it to query multiple API endpoints and am only returning 188 metrics. I notice in the docker logs that is a constant barrage of errors and log output. Is this being saved to a file?

**Comment by SuperQ** [comment]
Docker writes the logs to those directories. If you could include a sample of the errors, it might help determine if the exporter is logging things incorrectly or not.

You can also use a [`max-size` parameter in your Docker run](https://docs.docker.com/config/containers/logging/configure/#configure-the-logging-driver-for-a-container).

**Comment by crockk** [comment]
Yeah, it was the log file in the `containers/{container_id}` directory for the exporter. The container spews errors messages because I'm using it to query multiple endpoints, however it applies all the JSONPath to every returned JSON... Even though it will error out a lot of them. I couldn't see any other way to do it except running multiple containers with a different configuration for each endpoint I need to query, which is less than ideal. Do you know is there any plan to implement applying certain JSONPath rules only to certain endpoints within the same config, rather than applying the JSONPath to all returned JSON?

**Comment by crockk** [comment]
I see this is an issue that would be solved by refactoring the code to support blackbox-style "modules" in the config, as per [this comment](https://github.com/prometheus-community/json_exporter/issues/86#issuecomment-818743853). Closing this issue.
